#!/usr/bin/env python3
"""Validate AgentPing protocol schemas, fixtures, and generated firmware limits."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator, FormatChecker

ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "protocol" / "v1" / "agentping.schema.json"
VALID_PATH = ROOT / "protocol" / "v1" / "fixtures" / "valid-messages.json"
INVALID_PATH = ROOT / "protocol" / "v1" / "fixtures" / "invalid-messages.json"
HEADER_PATH = ROOT / "firmware" / "src" / "agentping_protocol_v1.h"


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)


def render_header(schema: dict[str, Any]) -> str:
    limits = schema["x-agentping-limits"]
    return f"""// Generated by protocol/validate.py --write-header. Do not edit manually.
#pragma once

#include <cstddef>
#include <cstdint>

namespace agentping::protocol_v1 {{
inline constexpr char kVersion[] = \"{schema['properties']['protocolVersion']['const']}\";
inline constexpr std::size_t kMaxMessageBytes = {limits['maxMessageBytes']};
inline constexpr std::size_t kMaxReplyCharacters = {limits['maxReplyCharacters']};
inline constexpr std::uint32_t kMaxClockSkewSeconds = {limits['maxClockSkewSeconds']};
inline constexpr std::size_t kMaxReplayWindowMessages = {limits['maxReplayWindowMessages']};
inline constexpr std::uint32_t kHeartbeatIntervalSeconds = {limits['heartbeatIntervalSeconds']};
inline constexpr std::uint32_t kApprovalTimeoutSeconds = {limits['approvalTimeoutSeconds']};
}}  // namespace agentping::protocol_v1
"""


def wire_size(message: dict[str, Any]) -> int:
    return len(json.dumps(message, ensure_ascii=False, separators=(",", ":")).encode("utf-8"))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-header", action="store_true", help="regenerate firmware limits header")
    args = parser.parse_args()

    schema = load_json(SCHEMA_PATH)
    Draft202012Validator.check_schema(schema)
    validator = Draft202012Validator(schema, format_checker=FormatChecker())
    max_bytes = schema["x-agentping-limits"]["maxMessageBytes"]

    expected_header = render_header(schema)
    if args.write_header:
        HEADER_PATH.write_text(expected_header, encoding="utf-8")
    elif not HEADER_PATH.exists() or HEADER_PATH.read_text(encoding="utf-8") != expected_header:
        print("firmware protocol header is stale; run protocol/validate.py --write-header", file=sys.stderr)
        return 1

    valid_messages = load_json(VALID_PATH)
    expected_types = set(schema["properties"]["type"]["enum"])
    actual_types: set[str] = set()
    for index, message in enumerate(valid_messages):
        errors = sorted(validator.iter_errors(message), key=lambda error: list(error.path))
        if errors:
            for error in errors:
                print(f"valid fixture {index} rejected at {list(error.path)}: {error.message}", file=sys.stderr)
            return 1
        size = wire_size(message)
        if size > max_bytes:
            print(f"valid fixture {index} exceeds {max_bytes} bytes: {size}", file=sys.stderr)
            return 1
        actual_types.add(message["type"])

    if actual_types != expected_types:
        print(f"fixture type coverage mismatch: expected {sorted(expected_types)}, got {sorted(actual_types)}", file=sys.stderr)
        return 1

    invalid_fixtures = load_json(INVALID_PATH)
    for fixture in invalid_fixtures:
        if not list(validator.iter_errors(fixture["message"])):
            print(f"invalid fixture was accepted: {fixture['name']}", file=sys.stderr)
            return 1

    oversized = dict(valid_messages[0])
    oversized["payload"] = dict(oversized["payload"])
    oversized["payload"]["softwareVersion"] = "x" * max_bytes
    if wire_size(oversized) <= max_bytes:
        print("oversize wire-message canary did not exceed configured bound", file=sys.stderr)
        return 1

    print(
        f"protocol validation passed: schema Draft 2020-12, "
        f"{len(valid_messages)} valid message kinds, {len(invalid_fixtures)} fail-closed fixtures, "
        f"max wire size {max_bytes} bytes, firmware header current"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
