// Generated by protocol/validate.py --write-header. Do not edit manually.
#pragma once

#include <cstddef>
#include <cstdint>

namespace agentping::protocol_v1 {
inline constexpr char kVersion[] = "1.0";
inline constexpr std::size_t kMaxMessageBytes = 16384;
inline constexpr std::size_t kMaxReplyCharacters = 512;
inline constexpr std::uint32_t kMaxClockSkewSeconds = 300;
inline constexpr std::size_t kMaxReplayWindowMessages = 256;
inline constexpr std::uint32_t kHeartbeatIntervalSeconds = 15;
inline constexpr std::uint32_t kApprovalTimeoutSeconds = 30;
}  // namespace agentping::protocol_v1
