import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
const browser=await chromium.launch({channel:'msedge',headless:true});
const errors=[];const page=await browser.newPage({viewport:{width:1440,height:1050}});
page.on('pageerror',e=>errors.push(e.message));
page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`)});
await fs.mkdir('test-results',{recursive:true});
try{
  await page.goto('http://127.0.0.1:5173');await page.waitForFunction(()=>window.pal, {timeout:60000});
  assert.deepEqual(await page.locator('#screen').evaluate(c=>[c.width,c.height]),[280,456]);
  await page.locator('#pause').click();
  const before=await page.evaluate(()=>pal.time);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>pal.time),before);
  await page.evaluate(()=>{pal.setState('idle');pal.renderAt(pal.time+2);});
  const startView=await page.evaluate(()=>pal.view);
  const startPose=await page.evaluate(()=>pal.pose);
  await page.evaluate(()=>{pal.setState('waiting');pal.renderAt(pal.time);});
  assert.deepEqual(await page.evaluate(()=>pal.view),startView,'entering attention must not snap the camera');
  assert.deepEqual(await page.evaluate(()=>pal.pose),startPose,'entering attention must not snap the body');
  await page.evaluate(()=>pal.renderAt(pal.time+.6));
  const midway=await page.evaluate(()=>pal.view);
  assert.ok(midway.viewport>228 && midway.viewport<456);
  await page.locator('#screen').screenshot({path:'test-results/transition-midpoint.png'});
  await page.evaluate(()=>{pal.setState('idle');pal.renderAt(pal.time);});
  assert.deepEqual(await page.evaluate(()=>pal.view),midway,'interrupted zoom must continue from its displayed position');
  await page.evaluate(()=>pal.renderAt(pal.time+2));
  assert.equal(await page.evaluate(()=>pal.view.viewport),456);
  const pictures=new Set();
  for(const state of ['startup','host_waiting','idle','running','waiting','completed','error','disconnected']){
    await page.locator(`[data-state=${state}]`).click();await page.evaluate(()=>pal.renderAt(pal.time+1.5));
    assert.equal(await page.evaluate(()=>pal.state),state);
    assert.equal(await page.locator(`[data-state=${state}]`).getAttribute('aria-pressed'),'true');
    pictures.add(await page.locator('#screen').evaluate(c=>c.toDataURL()));
    await page.locator('#screen').screenshot({path:`test-results/${state}.png`});
  }
  assert.equal(pictures.size,8,'each expression must change the actual rendered output');
  await page.locator('[data-state=waiting]').click();await page.evaluate(()=>pal.renderAt(pal.time+1));
  assert.ok(await page.evaluate(()=>pal.camera.top-pal.camera.bottom<1.1),'attention must zoom closer');
  const badges=new Set();
  for(const agent of ['codex','claude','copilot']){
    await page.locator('#agent').selectOption(agent);await page.evaluate(()=>pal.renderAt(pal.time));
    badges.add(await page.locator('#screen').evaluate(c=>c.toDataURL()));
    await page.locator('#screen').screenshot({path:`test-results/attention-${agent}.png`});
  }
  assert.equal(badges.size,3);
  await page.evaluate(()=>pal.renderAt(pal.time,pal.bubbleDeadline-1));
  assert.equal(await page.evaluate(()=>pal.bubbleVisible),true);
  await page.evaluate(()=>pal.renderAt(pal.time,pal.bubbleDeadline));
  assert.equal(await page.evaluate(()=>pal.bubbleVisible),false,'bubble must expire even while animation is paused');
  assert.equal(await page.evaluate(()=>pal.state),'waiting','timeout must not resolve attention');
  await page.locator('#screen').press('Enter');
  assert.equal(await page.evaluate(()=>pal.bubbleVisible),true,'tap must reopen pending request');
  await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  await page.locator('#message').fill('Please review this change before I continue. '.repeat(12));
  await page.evaluate(()=>pal.renderAt(pal.time));
  assert.ok(await page.evaluate(()=>pal.messagePages>1),'long messages must paginate');
  const bubbleBefore=await page.locator('#screen').evaluate(c=>c.toDataURL());
  await page.locator('#screen').press('Enter');await page.evaluate(()=>pal.renderAt(pal.time));
  assert.equal(await page.evaluate(()=>pal.messagePage),1);
  assert.equal(await page.evaluate(()=>pal.state),'waiting');
  assert.notEqual(await page.locator('#screen').evaluate(c=>c.toDataURL()),bubbleBefore);
  await page.locator('#screen').screenshot({path:'test-results/bubble-long-message.png'});
  await page.locator('#message').fill('Can I run the project tests before continuing?');
  await page.evaluate(()=>pal.renderAt(pal.time));
  assert.equal(await page.evaluate(()=>pal.messagePage),0);
  await page.locator('#screen').screenshot({path:'test-results/bubble-attention.png'});
  await page.locator('[data-state=error]').click();await page.evaluate(()=>pal.renderAt(pal.time+1));
  assert.ok(await page.locator('#message').inputValue());
  await page.locator('#screen').screenshot({path:'test-results/bubble-error.png'});
  await page.locator('[data-state=waiting]').click();
  await page.evaluate(()=>pal.renderAt(pal.time+100));assert.equal(await page.evaluate(()=>pal.state),'waiting');
  await page.locator('#resolve').click();assert.equal(await page.evaluate(()=>pal.state),'running');
  await page.locator('[data-state=idle]').click();await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  const topRow=await page.locator('#screen').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,280,30).data));
  assert.ok(topRow.every((value,index)=>index%4===3?value===255:value<=34),'header area contains only the faint background, with no branding or indicators');
  await page.screenshot({path:'test-results/showcase.png',fullPage:true});
  await page.locator('#framing').selectOption('full');await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  await page.locator('#screen').screenshot({path:'test-results/full-character.png'});
  await page.locator('summary').click();
  const faceOn=await page.locator('#screen').evaluate(c=>c.toDataURL());
  await page.locator('#face').uncheck();await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  assert.notEqual(await page.locator('#screen').evaluate(c=>c.toDataURL()),faceOn);
  await page.locator('#face').check();await page.locator('#yaw').fill('35');await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  await page.locator('#framing').selectOption('portrait');await page.evaluate(()=>pal.renderAt(pal.time+1.5));
  await page.locator('#screen').screenshot({path:'test-results/turned.png'});
  await page.locator('#reset').click();
  await page.locator('#scale').selectOption('1');assert.equal(await page.locator('#screen').evaluate(c=>c.getBoundingClientRect().width),280);
  const downloadPromise=page.waitForEvent('download');await page.locator('#capture').click();
  const download=await downloadPromise;await download.saveAs('test-results/export.png');
  const png=await fs.readFile('test-results/export.png');assert.equal(png.readUInt32BE(16),280);assert.equal(png.readUInt32BE(20),456);
  await page.locator('#sequence').click();assert.equal(await page.evaluate(()=>pal.paused),false);
  await page.locator('[data-state=error]').click();assert.equal(await page.locator('#sequence').textContent(),'Play a little workday ↗');
  await page.locator('[data-state=idle]').click();await page.locator('#pause').click();
  await page.locator('#scale').selectOption('2');
  for(const width of [320,375,414,768]){
    await page.setViewportSize({width,height:1000});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow at ${width}`);
    const bounds=await page.locator('#screen').boundingBox();assert.ok(Math.abs(bounds.width/bounds.height-280/456)<.001);
    await page.screenshot({path:`test-results/width-${width}.png`,fullPage:true});
  }
  const reduced=await browser.newPage({reducedMotion:'reduce'});await reduced.goto('http://127.0.0.1:5173');await reduced.waitForFunction(()=>window.pal);assert.equal(await reduced.evaluate(()=>pal.paused),true);
  assert.deepEqual(errors,[]);
  console.log('PASS: FBX load, eight distinct states, pause, face toggle, framing, rotation, native export, sequence cancellation, four responsive widths, reduced motion.');
}finally{await browser.close();}
